<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Deliveries</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 0; padding: 40px; background: #f8f9fa; color: #212529; } .container { max-width: 1100px; margin: 0 auto; } .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 24px; } h1 { margin: 0; } .description { color: #6c757d; margin-top: 6px; } .button { display: inline-block; padding: 10px 16px; background: #212529; color: white; text-decoration: none; border: 0; border-radius: 6px; cursor: pointer; } .table-container, .state-message { background: white; border: 1px solid #dee2e6; border-radius: 8px; overflow: hidden; } table { width: 100%; border-collapse: collapse; } th, td { padding: 14px 16px; text-align: left; border-bottom: 1px solid #dee2e6; } th { background: #f1f3f5; font-weight: 600; } tr:last-child td { border-bottom: none; } .actions a, .actions button { margin-right: 10px; color: #212529; } .actions button { background: none; border: 0; padding: 0; cursor: pointer; font: inherit; text-decoration: underline; } .state-message { padding: 32px; margin-bottom: 20px; text-align: center; } .state-message h2 { margin-top: 0; } .state-message p { color: #6c757d; } .error-state { border-color: #dc3545; }
    </style>
</head>
<body><main class="container">
    <header class="header"><div><h1>Deliveries</h1><p class="description">Track and manage water product deliveries.</p></div><a href="/deliveries/create" class="button">Add Delivery</a></header>
    <section id="action-feedback" class="state-message" aria-live="polite" hidden><p id="action-message"></p><button id="retry-delete" type="button" class="button" hidden>Try Cancel Again</button></section>
    <section id="loading-state" class="state-message" aria-label="Loading delivery list"><h2>Loading deliveries...</h2><p>Please wait while the delivery records are being loaded.</p></section>
    <section id="empty-state" class="state-message" aria-label="Empty delivery list" hidden><h2>No deliveries yet</h2><p>There are currently no deliveries registered in the system.</p><a href="/deliveries/create" class="button">Add Delivery</a></section>
    <section id="error-state" class="state-message error-state" aria-label="Delivery list error" hidden><h2>Unable to load deliveries</h2><p id="error-message">Something went wrong while loading the delivery records.</p><button id="try-again" type="button" class="button">Try Again</button></section>
    <section id="list-state" class="table-container" aria-label="Delivery list" hidden><table><thead><tr><th>ID</th><th>Customer ID</th><th>Delivery Date</th><th>Status</th><th>Actions</th></tr></thead><tbody id="delivery-rows"></tbody></table></section>
</main><script>
const states = { loading: document.getElementById('loading-state'), empty: document.getElementById('empty-state'), error: document.getElementById('error-state'), list: document.getElementById('list-state') }, rows = document.getElementById('delivery-rows'), errorMessage = document.getElementById('error-message'), feedback = document.getElementById('action-feedback'), actionMessage = document.getElementById('action-message'), retryDelete = document.getElementById('retry-delete');
function showState(name) { Object.entries(states).forEach(([key, element]) => { element.hidden = key !== name; }); } function cell(value) { const e = document.createElement('td'); e.textContent = value == null ? '' : String(value); return e; } function actions(id) { const e = document.createElement('td'); e.className = 'actions'; [['View', '/deliveries/'], ['Edit', '/deliveries/edit/']].forEach(([label, path]) => { const a = document.createElement('a'); a.href = path + encodeURIComponent(String(id)); a.textContent = label; e.append(a); }); const remove = document.createElement('button'); remove.type = 'button'; remove.textContent = 'Cancel'; remove.addEventListener('click', () => cancelDelivery(id, remove)); e.append(remove); return e; }
function feedbackMessage(message, canRetry, retry) { actionMessage.textContent = message; retryDelete.hidden = !canRetry; retryDelete.onclick = retry || null; feedback.hidden = false; }
function requestError(status) { if (status === 403) return 'You are not authorized to cancel this delivery.'; if (status === 404) return 'This delivery was not found. Refresh the list and try again.'; if (status === 422) return 'The cancel request was invalid.'; if (status >= 500) return 'The server could not cancel this delivery. Please try again.'; return 'Unable to cancel this delivery. Please check your connection and try again.'; }
async function cancelDelivery(id, button) { if (!window.confirm('Cancel this delivery?')) return; button.disabled = true; button.textContent = 'Cancelling...'; feedbackMessage('Cancelling delivery...', false); const retry = () => cancelDelivery(id, button); try { const response = await fetch('/api/deliveries/' + encodeURIComponent(String(id)), { method: 'DELETE', headers: { Accept: 'application/json' } }); if (!response.ok) { feedbackMessage(requestError(response.status), true, retry); return; } feedbackMessage('Delivery cancelled successfully.', false); await loadDeliveries(); } catch (error) { feedbackMessage('Network error while cancelling the delivery.', true, retry); } finally { button.disabled = false; button.textContent = 'Cancel'; } }
async function loadDeliveries() { showState('loading'); try { const response = await fetch('/api/deliveries', { headers: { Accept: 'application/json' } }); if (!response.ok) throw new Error('The delivery service returned an error.'); const payload = await response.json(); if (!payload || !Array.isArray(payload.data) || payload.data.some(item => !item || item.id == null)) throw new Error('The delivery service returned an invalid response.'); rows.replaceChildren(); payload.data.forEach(delivery => { const row = document.createElement('tr'); row.append(cell(delivery.id), cell(delivery.customer_id), cell(delivery.delivery_date), cell(delivery.status), actions(delivery.id)); rows.append(row); }); showState(payload.data.length ? 'list' : 'empty'); } catch (error) { errorMessage.textContent = error instanceof Error ? error.message : 'Please try again later.'; showState('error'); } }
document.getElementById('try-again').addEventListener('click', loadDeliveries); loadDeliveries();
</script></body></html>
